drop trying to output version from exec, test output

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -63,7 +63,7 @@ jobs:
       - name: Pull and run Docker image
         env:
           VERSION: ${{ needs.bump-version.outputs.NEW_VERSION }}
-          EXPECTED_OUTPUT: "Mr. K says: \"World, Hold on!\" (Version: $VERSION)"
+          EXPECTED_OUTPUT: "Mr. K says: \"World, Hold on!\""
         run: |
           docker pull jamoos/graal:$VERSION
           ACTUAL_OUTPUT=$(docker run --rm jamoos/graal:$VERSION)
@@ -71,11 +71,11 @@ jobs:
           echo $ACTUAL_OUTPUT
           # need to figure out why the version env var is not being parsed here...
 
-          # if [ "$ACTUAL_OUTPUT" = "$EXPECTED_OUTPUT" ]; then
-          #   echo "Test passed: Output matches expected value."
-          # else
-          #   echo "Test failed: Output does not match expected value."
-          #   echo "Expected: $EXPECTED_OUTPUT"
-          #   echo "Actual: $ACTUAL_OUTPUT"
-          #   exit 1 
-          # fi
+          if [ "$ACTUAL_OUTPUT" = "$EXPECTED_OUTPUT" ]; then
+            echo "Test passed: Output matches expected value."
+          else
+            echo "Test failed: Output does not match expected value."
+            echo "Expected: $EXPECTED_OUTPUT"
+            echo "Actual: $ACTUAL_OUTPUT"
+            exit 1 
+          fi
