add test docker job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -55,3 +55,25 @@ jobs:
                         -t jamoos/graal:$VERSION .
           docker push jamoos/graal:latest
           docker push jamoos/graal:$VERSION
+
+  test-docker:
+    runs-on: ubuntu-latest
+    needs: build-docker
+    steps:
+      - name: Pull and run Docker image
+        env:
+          VERSION: ${{ needs.bump-version.outputs.NEW_VERSION }}
+          EXPECTED_OUTPUT: "Mr. K says: \"World, Hold on!\" (Version: $VERSION)"
+        run: |
+          docker pull jamoos/graal:$VERSION
+          ACTUAL_OUTPUT=$(docker run --rm jamoos/graal:$VERSION)
+          echo "Actual Output:"
+          echo $ACTUAL_OUTPUT
+          if [ "$ACTUAL_OUTPUT" = "$EXPECTED_OUTPUT" ]; then
+            echo "Test passed: Output matches expected value."
+          else
+            echo "Test failed: Output does not match expected value."
+            echo "Expected: $EXPECTED_OUTPUT"
+            echo "Actual: $ACTUAL_OUTPUT"
+            exit 1 
+          fi
